hadley/adv-r

Functions.rmd
=> Fixing a typo: lapply -> sapply

www/highlight.css
https://github.com/hadley/adv-r/issues/644
=> Make navigation width responsive to screen width

index.rmd
=> Fixed minor typo

Environments.rmd
=> Fixed typo

Rcpp.rmd
=> Caught a typo

Style.rmd
yihui moved formatR introduction
=> fixed link to formatR

Computing-on-the-language.rmd
Which part of the documentation?
Maybe even mention `width.cutoff`…
=> more specific

Profiling.rmd
Amazon links were broken. This fixes them.
=> fix amazon links in Profiling.rmd

Computing-on-the-language.rmd, Exceptions-Debugging.rmd
Apparently I had some other small edits lying around; I consult this book often!
=> Fixes #697, the garbled exercise involving plyr::.

Computing-on-the-language.rmd
=> Fixing sentence

memory.rmd
What's the "it" and why is "it" important? (otherwise relative to what?)
=> What's "it"?

Data-structures.rmd
Described the case when names() returns NA, as a result of adding some, but not all names after the creation of a vector.
=> names() can return NA

Style.rmd
Changed "This will cause" --> "Doing so will cause"
=> Change wording of reference to previous sentence

S4.rmd
Some of the code in this page was highlighted; I highlighted the rest.
=> Add Code Highlighting

Function-operators.rmd
`plyr::partial()` should be `pryr::partial()`.
=> fix typo in package name

Functionals.rmd
I could be mistaken about the form used here, but I think this sentence makes more sense using "addition" rather than "additional."
=> Changed form of "additional"

Computing-on-the-language.rmd
=> Fixed typo in Non-standard evaluation chapter

Profiling.rmd
=> Fix typo: ouput => output

Exceptions-Debugging.rmd
The "this" in the original text confused me, I have made the text more verbose.
The example now also obeys the suggested "best practice".
=> Clarify restrictions when signalling conditions

OO-essentials.rmd
The latter now contains detailed discussion of virtual classes
=> change outdated ?Classes to ?setClass

Functionals.rmd
The code of vapply2 has the problem of not only `out` should be transposed but also the initiation of out is wrong in essense.
=> an error in chapter Functionals

Environments.rmd
The code is changing e$a, but the image is showing e$b as being changed.
=> Small typo on Environments.rmd

S3.Rmd
Seems like it would be handy to mention this at first occurrence.
=> Mention list/scalar possibility for classes early.

OO-essentials.Rmd
=> fix small typos in OO-essentials.Rmd

S3.Rmd
not a glorious edit but hopefully a useful one. fantastic book!
=> point out typos: 'howver' and 'subtclass'

S3.Rmd
(I think these are correct corrections...)
=> Fix some inconsistencies in R examples.

S3.Rmd
=> Fix a typo

S4.Rmd
The S4 section LGTM, no major issues.
I marked any comments inline with `JH:`, other changes were just typos / spelling.
=> Add notes about S4 section

S4.Rmd
Just fixin' some typos. Really enjoying the S4 chapter so far.
=> S4/Validator: Fix typos

S4.Rmd
"I assign the copyright of this contribution to Hadley Wickham".
Cheers, and thanks for great work-
Wolfgang
=> Fixed typo in the spelling of Bioconductor

OO-tradeoffs.Rmd, R6.Rmd, S3.Rmd, S4.Rmd, base-types.Rmd, index.Rmd
"I assign the copyright of this contribution to Hadley Wickham".
Fix typo's
Grammatical corrections and improvements
=> Corrections for chapters in the OOP section

R6.Rmd
This PR adds a section on active fields, when and how to use them
=> Add section on active fields

Environments.Rmd
The last 3 commits are questions/comments. If you just want the small edits, I'm happy to reset this branch or you can cherrypick/merge just those.
=> Tweaks to environments

R6.Rmd
=> fixed a typo

OO.Rmd, S3.Rmd, base-types.Rmd
I read the intro (and a bit beyond). I think it gives a very useful overview of the OOP scene. PR is just a few copy edits and html-commented questions that popped into my mind.
A big-picture question I'll just leave here:
Is is possible to say at a very high-level what sorts of tasks each system is suited for? Like, is there any interesting anecdote re: why BioC embraced S4? When do people tend to turn to R6? I.e. why was it chosen for httr?
=> Small edits to first sections of OO chapter

R6.Rmd
Added info about deep cloning in R6, and created a full subpart about cloning.
=> Clone & deep clone

R6.Rmd
Added info about the `set` method
=> Set method

base-types.Rmd
=> Fix title for base-types-2

OO-tradeoffs.Rmd
"is" to "if" and remove unnecessary "because". I assign the copyright in this edit to Hadley Wickham.
=> Fix 2 typos in OO-tradeoffs.Rmd

Expressions.Rmd
a collection of small proofreading edits
=> Proofreads existing Expressions.Rmd

Quotation.Rmd
As is code produces
"Good Hadley morning"
=> Arguments reversed in paste

Expressions.Rmd
Just fixing a small batch of typos.
=> Fixing some Typos in chapter 18

Evaluation.Rmd
both expressions are evaluated.
=> typo conjunction

Quotation.Rmd
Some minor fixes from a read-through of the polite fiction. 
=> various typos in Quotation.Rmd

Environments.Rmd
All minor, most notable (though still minor):
* Remove renegade "I".
* when ever ⇨ whenever.
* Move up "the context" to make the frag. more readable.
=> Copy edits for Ch. 7, Environments.

Names-values.Rmd
=> Typos in Name-Value Section

Expressions.Rmd
=> typo and sentence adjustment in Expression.Rmd

Data-structures.Rmd
Not sure if this is needed for such a minor change but I assign the copyright of this contribution to Hadley Wickham.
=> Typo in lists

Introduction.Rmd
Updated links in Conventions and Colophon sections to point to second edition of book (My apologies if the links to the first edition were intentional.) I assign the copyright of this contribution to Hadley Wickham
=> Link to 2nd edition

Quotation.Rmd
PS: I have made a couple of small pull requests with typos in this chapter now. If it is preferable that I rather collect such corrections into one slightly larger pull request, please let me know, and I'll adjust in the future.
=> Some typos near the end of Quotation.Rmd

Quotation.Rmd
=> Typos in Quotation, Section 21.7

Quotation.Rmd
=> Typos in Quotation.Rmd

Quotation.Rmd
From *... that different only slightly ...* to *... that differ only slightly ...*.
=> Small typo fix in Quotation.Rmd

Names-values.Rmd
What happens when you run this code?
=> Add ? mark to question

Functions.Rmd
- few grammar/punctuation/typo fixes
- one very minor suggestion to change order of function components for consistency
=> Edits functions

Quotation.Rmd
The code does not correspond with the tree shown in the figures:
* Line 352
* Line 363
=> Tiny edits and missmatching code and figure

Names-values.Rmd
subject verb agreement by number
=> add "s" : form that looks like

book/tex/Introduction.tex
=> Broken link to SICP book

Data-structures.Rmd
=> typo correction

Quotation.Rmd
=> Typo in Quotation.Rmd

Evaluation.Rmd
=> Some typos in Evaluation.Rmd

Evaluation.Rmd
=> Typos in Evaluation.Rmd / Quosures

Evaluation.Rmd
=> Spelling fix in Evaluation.Rmd / Data Masks

Evaluation.Rmd
=> Typos in Evaluation.Rmd / Performance

Evaluation.Rmd
I assign the copyright of this commit to Hadley Wickham
=> Typo in Evaluation.Rmd exercise

Evaluation.Rmd
=> Typos in Evaluation.Rmd / Wrapping

Performance.Rmd
=> Writing TRUE instead of T

Preface.Rmd
This is my first PR. I assign the copyright of this contribution to Hadley Wickham.
=> Fixed typo in Programming paradigms

Environments.Rmd
"you them modify" to "you modify them"
=> Typo in environment modification

Environments.Rmd
Is this level of typo editing helpful?
=> Typo in getting and setting

Environments.Rmd
=> Typo in special environment introduction

Environments.Rmd
=> Typo in the function environment

Environments.Rmd
=> Typo in function binding

Functions.Rmd
The answer to this quiz question  is about the code, not all possible calls to the function.
I assign the copyright of this "contribution" to Hadley Wickham.
=> refine quiz question

base-types.Rmd
=> Fixed typos in base-types

Environments.Rmd
=> Little typo in Environments

Profiling.Rmd
=> Small fixes to Profiling.Rmd

Evaluation.Rmd
=> Typo in Evaluation.Rmd

Vectors.Rmd
=> Minor typo fixes to Vectors.Rmd

R6.Rmd
=> minor typo make -> may

OO-tradeoffs.Rmd
=> OO-tradeoffs typo fix

OO.Rmd
This is one of those grammar things that makes me doubt myself, because I think it might be fine to drop `of` in speech.  In any case, I think it reads a bit better with it.
=> Added `of`

Vectors.Rmd
There were letters missing, but I think I found them and am now returning them home.
I assign the copyright of this contribution to Hadley Wickham.  
Even if I'm confident he would have found them on his own ¯\\\_(ツ)_/¯
=> Fix typos in Vectors.Rmd

Foundations.Rmd, Names-values.Rmd, Vectors.Rmd
I assign the copyright of this contribution to Hadley Wickham. 
:)
=> fix a few small typos

Quotation.Rmd
=> Correct typo

Functions.Rmd
I assign the copyright of this contribution to Hadley Wickham :)
=> Fix typos in Chapter 6 Functions

Quotation.Rmd, Subsetting.Rmd, Vectors.Rmd
thanks for the great work
oh and yes, I assign the copyright of this contribution to Hadley Wickham. ;-)
=> just fixing some typos

S3.Rmd
If you accept this, I'll submit a few more similar changes.
Commentary on "try and":
http://www.macmillandictionaryblog.com/try-to-get-over-try-and
=> Change "try and" into "try to"

OO-tradeoffs.Rmd
=> capitalization of 'JavaScript'

Environments.Rmd, Functions.Rmd, Quotation.Rmd, S4.Rmd, Subsetting.Rmd
=> Change "try and" to "try to" or similar.

Functions.Rmd
Link in the middle of the sentence?
=> Functions:Introduction:Quiz

Function-factories.Rmd
=> Remove extra hashtag in ref

Names-values.Rmd
Changed Line 717 from 
1.  It occupies about 4 MB.
to
1.  It occupies about 8 MB.
=> fix a typo in Answers

Names-values.Rmd
"I assign the copyright of this contribution to Hadley Wickham". (Not sure if this is required for such a small change, but whatever)
=> Fix typo (punctuation)

Conditions.Rmd
=> Fix typos in chapter Conditions

Vectors.Rmd
=> Typo fixes in Vectors

Names-values.Rmd
=> One "but" is enough

Subsetting.Rmd
=> Subsetting fixes

Conditions.Rmd
=> Conditions fixes

Functions.Rmd
=> Functions fixes

Functionals.Rmd
=> Functionals fixes

Function-factories.Rmd
=> Function factories fixes

Function-operators.Rmd
=> Function operators fixes

base-types.Rmd
=> Base types fixes

OO-tradeoffs.Rmd
=> OO tradeoffs fixes

Meta.Rmd
=> Meta fixes

Expressions.Rmd
=> Expressions fixes

Quotation.Rmd
=> Quotation fixes

Introduction.Rmd
Added links to the online version of the books and resources (R4DS, R packages, and the Tidyverse).
It would still be interesting to introduce the work with a paragraph or two. But I'm not sure of the wording so I leave that for others.
=> Add links in the related work section

Evaluation.Rmd
=> Evaluation fixes

Translation.Rmd
=> Translation fixes

S4.Rmd
=> Reviewing S4 chapter

Function-factories.Rmd
missing {} brackets after '_' subscript in La…TeX formula.
Without this change could not generate pdf output due to latex errors.
=> Fixed pdf output error

Function-factories.Rmd, Introduction.Rmd, OO.Rmd, Preface.Rmd, R6.Rmd, S3.Rmd
Completing some ref changes started in b12fd37 re: the chapter on R6. Also fixing one typo.
=> Fix r6 refs

Expressions.Rmd
Faux PR with my comments on the Expressions chapter (which I'll better explain when we have our meeting)
=> Comment on Expressions chapter

Introduction.Rmd
Also use the generally accepted form of "R-Ladies"
=> Fix typos in Introduction.Rmd

Introduction.Rmd
Change:
"who have made a wonderfully welcoming community for women and other gender minorities"
to:
"who have made a wonderfully welcoming community for women and gender minorities"
At about 50% of the global population, women are not a gender minority :stuck_out_tongue:
=> Correction: "women" is not a gender minority

Foundations.Rmd, Introduction.Rmd, Names-values.Rmd
**Introduction.Rmd**
- Remove double verbs
- Fix minor typo
**Foundations.Rmd**
- Fix 2 minor typos
**Names-values.Rmd**
- correct word inversion "will lead to you make"
- replace present tense with past subjunctive to express unreal clause after "as if"
=> Typos in Introduction.Rmd, Foundations.Rmd, and Names-values.Rmd

Translation.Rmd
I think I'd need a week to go through the whole metaprogramming suite in detail, working through all the exercises, to really become comfortable with it, but I'm glad it's all in one place.
=> Comments on translation chapter

Vectors.Rmd
Wildcards for is.*() or as.*() functions?
=> Vectors:Atomic vectors

Control-flow.Rmd
=> least-expression -> least-expressive

Control-flow.Rmd
Pretty sure this is what you meant to say
=> Fix wording

Vectors.Rmd
=> Fix small typo

Vectors.Rmd
Might be a regression from a previous version.
=> Redundant &  missplaced footnote

Control-flow.Rmd
- typo: is instead of if
- unneeded comma
- remove unnecessary words
=> Minor fixes

S3.Rmd
https://adv-r.hadley.nz/s3.html#helpers
=> a typo in 13.3 Classes

OO-tradeoffs.Rmd, OO.Rmd, R6.Rmd, S3.Rmd, S4.Rmd
I just read this section to prepare for some of the talks today, and I found a few typos and possible typos. Freshly inspired by David Robinson's wonderful keynote on open work, I wanted to contribute some fixes. Hope they're helpful.
These chapters were really fascinating to read. Thanks for all your work on this. I assign the copyright of this contribution to Hadley Wickham.
=> Fixes to typos and possible typos in OOP section

Subsetting.Rmd
The alignment of the online html version of table in 4.3.3 is hard to read.
=> Subsetting: Selecting a single element

Conditions.Rmd
=> typo in line 397

Control-flow.Rmd
In Line 38, "`perform_action` is called once for each item in `vector`, rebinding the value of `item` each time.", what do you mean by "rebinding"? incrementing?
=> Control-flow: Loops & Answers

Environments.Rmd
Either keep “list” or “see.” But both don’t seem to make sense.
=> Minor typo fix.

Preface.Rmd
some typos in the description of the Vectors chapter
=> fixing some typos!

latex/preamble.tex
This small change should remove widow lines throughout the book.
=> Remove widow lines

Conditions.Rmd
* p. 177 Aks to define web API (similar comment in Subsetting). Is it necessary?
=> Conditions

Introduction.Rmd, latex/preamble.tex
* "You’ll also understand the dangers and when to avoid it." (p. 4)
The editor ask to change "it" to "them" because she understood as refering
to "the dangers". I interpret that is refers to "metaprogramming" so I kept
it as is.
* @kfeng123's name (电线杆) has chineese characters. I added the xeCJK package to the
LaTeX preamble but I also needed to install the FandolSong-Regular font
(https://ctan.org/tex-archive/fonts/fandol?lang=en) into my system.
BTW, I don't envy Alice's work of having to comb through that massive list of
names and handles 😅.
=> Introduction

Evaluation.Rmd, Expressions.Rmd
I hope I changed them to the correct wording :grimacing:
\ - Josh
=> Minor typos

Function-factories.Rmd
* p. 257 Editor asks for an explanation of the Figure
* p. 259 Editor asks to remove quotes around "optimal". I feel that this removes the implication that it's not really "optimal" as stated in the footnote. Changed it to "so-called optimal".
=> Function factories

R6.Rmd
use then make TO use them to make
=> Spelling in R6

Big-picture.Rmd
The style of outline of this chapter is not the same as the others. In previous chapters sections are describe as "Section 1 shows how to... " but here it's "Section 1: Code is data...".
=> Big picture

latex/preamble.tex
This changes figures and table names to "Figure" and "Table".
=> Changes figures and tables names

Evaluation.Rmd
way to way to write TO way to write
=> Spelling in Evaluation-ch.

R6.Rmd
=> forgot word

Function-operators.Rmd
* p.271 Editor asks for "for loop" to be written in monospace font. I left it as is.
=> Function operators

Functionals.Rmd
**p. 211** The editor ask to close the space between "sea" and the question mark. I think the she can't see the emojis on her pdf viewer. 
**p. 223** The editor ask to describe a table in the text. This is a major change on the paragraph, do you want me to do write it?
=> functionals

Evaluation.Rmd
The first one already reported and not accepted (I think it was probably overlooked).
=> 2 typos  in Evaluation.Rmd

Big-picture.Rmd
Scary, my first ever fork and commit! Hope I'm doing it right! All the best from Zurich!
=> Typo call > can

Names-values.Rmd
Text refers to 1000 while R code refers to 100. Make both consistent to R example
=> Update string pool banana example text

Functionals.Rmd
Love the book so far, thank you!
=> Very minor typo in Functionals

Control-flow.Rmd
"What is the different..." -> What is the difference..."
=> Typo in Control-flow.Rmd

S4.Rmd
=> Fix grammar errors (2)

Introduction.rmd
The link previously pointed back to this same 1st edition.
=> Correct the link to the second edition.

Conditions.Rmd
"it's useful to provide" instead of "it's useful provide"
=> Added a missing "to"

Functionals.Rmd
Actually, I don't quite understand this part: .x and .y. for two argument functions, and ..1, ..2, ..3, etc, for functions with an arbitrary number of arguments.
=> what is ".y."

Functionals.Rmd
I think this variable is better to be called "slopes" since the function is extracting the coefficient of "wt".
=> Variable name change: "intercepts" to "slopes"

Big-picture.Rmd
Add "it" to make the meaning clearer. 
=> Add "it" to a sentence in Big-picture.Rmd

Environments.Rmd
I think this contributes to the readability. I had to read the sentence twice before this change (maybe also because EN is not my mother tongue).
=> Emphasize term

Style.rmd
Point to the tidyverse style guide instead of the 2nd edition
=> Style guide URL fix

Conditions.Rmd
"worry getting caught" -> "worry about getting caught"
=> Typo in Conditions.Rmd

Conditions.Rmd
=> Hyphenate "user-facing"

Vectors.Rmd
simplystatistics.org website has been updated which broke one of the URL in the Vectors.Rmd file.
=> Fix broken link to simplystatistics.org blog post

Conditions.Rmd
=> Typo in function name

Vectors.Rmd
I think the omission is intentional, but it might warrant a footnote.
=> Mention NA_complex_ as a footnote

Function-operators.Rmd
`meomoise()` changed to `memoise()`.
=> Update Function-operators.Rmd -  Section 11.3

Foundations.Rmd
change "six chapters" to "seven chapters"
=> fix typo in intro
