hadley/adv-r

- beyond-exception-handling.rmd
* from `malformed_log_entry_error()` I inferred that `...` in `condition()` should be used to pass further elements to the underlying `list` which is returned
* some anonymous functions used in `tryCatch()`, `withRestarts()` and `withCallingHandlers()` didn't take any arguments, whereas in fact they should take one
> small bugfixes in beyond-exception-handling.rmd

- OO-essentials.rmd
In `t.test`, if it was an S3 method, "test" would refer to the class, not "t'.
> method name <-> class name

- _layouts/default.html
Capitalize Amazon for consistency, remove trailing period.
> Minor formatting fixes on Amazon book link

- Profiling.rmd
The function should have both the data frame and number of observations passed as arguments. Currently, it has neither.
Same as #706, except this request maintains `q` as an argument and removes the global dependency on `n`.
> Profiling.Rmd: Updating typos to s5q6

- Profiling.rmd
Hello Hadley,
I think in this case it should be `getMethod` instead of `findMethod` to avoid S4 method dispatch. `findMethod` returns the environment (as a list) that contains the method and not the method itself, and I don't know how to get the method from the environment. Please clarify.
Cheers,
Alex
> Use getMethod to avoid S4 method dispatch

- Exceptions-Debugging.rmd
A typo in the section on custom conditions. Accidentally it produced the correct result in the output.
> custom_stop, not customStop

- Environments.rmd
This set of proposed changes is admittedly pedantic - but I noticed that you made the point earlier that the objects live outside the environment. This is a very useful point.
I tried to find a way to rephrase the first two items such that they could not confuse this earlier point.
> Differences between environments and lists

- Functions.rmd
If the code snippet is not evaluated, than x remains the same, as in 789 line.
In other words, the second element remains 6, because line 799 is not evaluated.
Therefore, printing x in line 814 will return "10 6 3 ..." instead of assumed "10 7 3 ..."
> Wrong output (6 instead of 7)

- Style.rmd
- Subsetting.rmd
Replaced one character versions of TRUE and FALSE for clarity and for reasons alluded too in Style.rmd line 60 (i.e. that T and F are not reserved words).
> replace logical T and F with TRUE and FALSE in Subsetting.rmd

- Data-structures.rmd
The text is talking about attribute names, not names of accessor functions.
> Remove parens from attribute names

- Exceptions-Debugging.rmd
Most importantly the fact that control flow continues normally after a non-exiting handler is called.
> Some precisions on tryCatch() vs withCallingHandlers()

- DESCRIPTION
- dsl.Rmd
Since Hadley's most recent update to ``dplyr`` and ``dbplyr``, the function ``translate_sql()`` is now provided by the package ``dbplyr``, not ``dplyr``.
> Use dbplyr not dplyr

- S4.Rmd
Behold, another typo. Along the way I noticed both "initialise" and "initialize" and wanted to suggest going with "initialize" as that's the name of the generic function.
> S4: Fix typo

- Functional-programming.Rmd
In the code block right before this one `na_value` is used, but now `na.value`. However, it seems they are indicating the same so changing the writing is confusing to me.
> Make na_value consistent

- base-types.Rmd
So that the order of the function types in the code chunk is the same as in the above description
> Re-order function types to match text

- Expressions.Rmd
Arithmetic error in "Operator precedence and associativity.
As is it introduces the concept of recursion which a lot of people won't be familiar with. I think the replacement text gets across the idea that a call can contain other calls without need to introduce the term recursion... which I don't think will be used elsewhere in the book.
> Typo and Call lists could be simplified

- S3.Rmd
Not sure if it's necessary, there's a forward reference a few paragraphs below. A set of rules feels definitive, adding "maybes" as crossrefs or even footnotes might help accuracy at the risk of being slightly too verbose.
> Add forward reference to "inheritance" section

- OO.Rmd
The phrase "...and a methods describe what something _do_" is a bit weird. It should either be singular throughout the whole statement or plural. I decided to go with the plural "methods" by simply removing the article "a" before it.
> Fixing a simple typo

- Quotation.Rmd
Most of these are simple typo fixes, but I did run into a bit of a problem following some of the conversation around `expr`, `enexpr`, and `exprs`. I tried to fill in what I thought was missing in some of those cases, but there's a very good chance that what I filled in is wrong, so feel free to discard as you see fit.
As always, I assign the copyright of this contribution to Hadley Wickham.
> Fixing some typos in chapter 19

- Functions.Rmd
[R 3.2.0 modified the behavior of lapply](https://stat.ethz.ch/pipermail/r-announce/2015/000583.html) to force its functions' arguments by default:
> Higher order functions such as the apply functions and Reduce() now force arguments to the functions they apply in order to eliminate undesirable interactions between lazy evaluation and variable capture in closures.
So this section needed to be brought up to date. I tried to change as little as possible, while still illustrating the potential problem and also mentioning that `lapply()` now does the same thing @hadley is recommending (forcing the functions' arguments).
Fixes #837.
> Update the `lapply` example in the Lazy Evaluation section (fixes #837)

- Subsetting.Rmd
The subsetting section's table says that subsetting a list (with `[`) with `NULL` returns `list(NULL)`, but it just returns `list()`.  This corrects that.
```r
as.list(1:4)[NULL]
```
> List + [ + NULL = list(), not list(NULL)

- Performance.Rmd
> Fix code typo in `Performance.Rmd`

- memory.Rmd
I was confused when I read this chapter because "??" is TeX for "reference not found" or "file not found".
> Change "?? bytes" to "variable number of bytes"

- R6.Rmd
active values definition referenced `name` where it should have been referencing the argument `value`
> correct R6 active fields example

- Expressions.Rmd
- "In rlang 0.2.0, `lang_standardise()` was soft-deprecated and renamed to `call_standardise()`."
> updated name of rlang-function

- Names-values.Rmd
GC deletes objects that _do not_ have bindings
> fix typo in 4.6.2 Memory Leaks

- Names-values.Rmd
If a deletion can even have a copyright, it's mos' def Hadley Wickham's. ✍️
> Remove redundancy from GC collector.

- Expressions.Rmd
what was described was the commutative rule, not the associative rule, for regular addition.
> associative rule for addition

- Evaluation.Rmd
Without `, data = data`, the following fails with an error as shown.
```
> subset3(iris, Species == "setosa")
Error in ~Species == "setosa" : object 'Species' not found 
```
> Without `data` argument, an error occurs

- Data-structures.Rmd
This is less confusing as it is consistent:
- with the default matrix argument order
`matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
dimnames = NULL)`
- with the corresponding vectorized form
`matrix(1:6, c(2, 3))`
> Swap order matrix arguments

- Data-structures.Rmd
Made attributes examples clearer since they were returning NULL and NULL, not giving the correct impression of loosing attributes.
> Add attributes(a) before examples

- Debugging.Rmd
When demonstrating the behavior of `withCallingHandlers()` via `message2error()`, a function `f()` is defined but never used. I updated the example to use this function. A later exercise (currently in [Conditions.Rmd](https://github.com/hadley/adv-r/blob/a36fa316a6040f8d27e7dff706b2348be250afd6/Conditions.Rmd)) compares the difference in the call stacks when `message2error()` is implemented with `withCallingHandlers()` versus `tryCatch()`. The difference is more noticeable when the message is produced within a nested function, i.e. the first entry `message2error(g())` in the traceback after using `tryCatch()` appears rather informative since `g()` itself contains the message.
> Use nested function to demonstrate message2error.

- Rcpp.Rmd
The link for "Rcpp is smoking fast for agent-based models in data frames" is dead, and it's now being rehosted at https://gweissman.github.io/babelgraph/blog/2017/06/15/rcpp-is-smoking-fast-for-agent-based-models-in-data-frames.html. I updated the link, although I understand if keeping the original link is more for citation than linking.
> Update "Rcpp is smoking fast..." link

- Introduction.Rmd
About a year ago, we started a GitHub repo of user groups (https://github.com/jumpingrivers/meetingsR/) The Revo blog (http://blog.revolutionanalytics.com/local-r-groups.html) points to the page.
> Update link to local groups

- Evaluation.Rmd
The example function threshold_var1 does not run the way it is defined now. Added "." in front of data, and changed the explanation of the code accordingly.
> Added missing dot to "data"

- base-types.Rmd
The way it is written in the bullet point, `is.array(x)` should return `FALSE` if `x` is a matrix. As far as I can tell, this is not correct, hence the suggested fix. Here is an example:
``` r
x <- matrix(rnorm(6), nrow = 3, ncol = 2)
length(dim(x))
#> [1] 2
is.array(x)
#> [1] TRUE
```
Quoting from the documentation for `is.array`: 
> is.array returns TRUE or FALSE depending on whether its argument is an array (i.e., has a dim attribute of positive length) or not.
> Is the is.array() function described correctly?

- Environments.Rmd
> Typo in explanation of environment ancestors

- Functionals.Rmd
I realize the designation of success versus failure for a Bernoulli trial is arbitrary, but if `p` is defined as the probability of success, then I think this code is counting the number of failures before the first success. This is consistent with the [description of the geometric distribution](https://en.wikipedia.org/wiki/Geometric_distribution#Introduction_to_the_geometric_distribution) in Wikipedia:
> Consider a sequence of trials, where each trial has only two possible outcomes (designated failure and success). The probability of success is assumed to be the same for each trial. In such a sequence of trials, the geometric distribution is useful to model the number of failures before the first success. The distribution gives the probability that there are zero failures before the …
> Change geometric distribution to number of failures before 1st success.

- Function-operators.Rmd
I believe that the for loops for adding elements to funs_m does not work as intended in these two examples. Here is the output from the current code: `funs_m` is first defined with two `NULL` elements, and then it gets two new elements, with names `mean` and `sum`, which are appended. It hence has length four.
``` r
delay_by <- function(delay, f) {
function(...) {
Sys.sleep(delay)
f(...)
}
}
funs <- list(mean = mean, sum = sum)
funs_m <- vector("list", length(funs))
for (fun in names(funs)) {
funs_m[[fun]] <- delay_by(funs[[fun]], delay = 0.1)
}
funs_m$mean(1:10)
#> [1] 55
length(funs_m)
#> [1] 4
names(funs_m)
#> [1] ""     ""     "mean" "sum"
```
With the proposed fix, we get this instead. By setting the names of `funs_m` equal to the names of `funs`, the functions are added to the …
> Adding elements to list does not work as intended

- Quotation.Rmd
in file Quotation.Rmd
Now the results of a conceptual exercise are kept hidden.
> fix typo and hide results of conceptual exercise

- Environments.Rmd
Removed the last "then" in "You'll then learn then about the function environment ...", as well as some other small fixes.
> Spelling fix in Environments.Rmd

- Evaluation.Rmd
I wonder if this example would be clearer for the reader if `env` was defined, even though it does not matter for the result of this function. Then  `eval_bare(x + y, env(x = 1000))` gives 12 while `eval_bare(expr(x + y), env(x = 1000))` gives 1002. 
As it is now, `eval_bare(expr(x + y), env = env)` fails, since `env` is a function, not an environment.
> Clarification of Evaluation example

- Evaluation.Rmd
According to the rlang documentation, as_env() has been soft-deprecated and renamed to as_environment(), hence suggesting a change.
> Use new function name

- Quotation.Rmd
Not sure if the expression was meant to be ‚as is’, since I am no native speaker.
Duckduckgoing "all we need to turn is turn" did not yield any result, giving me confidence it is meant to be as proposed here.
Please excuse inconvenience, if so, and thank you for the nice read!
> Grammar corrected

- Vectors.Rmd
In `Vectors.Rmd`:
> Attributes should generally be thought of as ephemeral (unless they’re formalised into an S3 class). For example, most attributes will be lost when you operate on a vector:
>
> ```
> attributes(a[1])
> #> NULL
>
> attributes(sum(a))
> #> NULL
> ```
>
> There are three exceptions for particularly important attributes:
>
> - Names, a character vector giving each element a name.
> - Dimensions, an integer vector, used to turn vectors into matrices and arrays.
> - Class, a character vector, used to implement the S3 object system.
From this, I initially got the impression that 
- class attributes are *always* retained on vector operations, or even that 
- for S3 objects, *all* attributes are retained
> Attributes should generally be thought of as ephemeral (unless they’re …
> explain that attr are lost on s3 classes, unless otherwise implemented

- Functions.Rmd
Since `enquos()` is now the recommended way to capture dots.
> Mention enquos() rather than quos()

- Quotation.Rmd
You use "the user" (singular) as the section continues, so I think it makes more sense this way.
Bonus fun fact: 'twas the only place you used "users'" in the whole book. 🕴
> Switch users' to singular possessive

- Introduction.Rmd
I added references to RStudio Community in the "Getting Help" section and added two sentences about using the `reprex` package to the bullet point about creating a reproducible example.
> Add RStudio Community to "getting help"

- FP.Rmd
n.b. I added the _is_ in https://github.com/batpigandme/adv-r/commit/a7cf4b0a25fcf1f972104926b290917a66d3d888#diff-ed8b1340d157a79b8555ae20e0459f2fR12
> A functional style tends to create functions that can easily be analysed in isolation (i.e. using only local information), and hence _**is**_ often much easier to automatically optimise or parallelise.
It's possible that the _is_ should be _are_ and the subject is _functions_ and not _A functional style_, but either way, I think there should be a verb there.
> Add missing words in FP intro

- Expressions.Rmd
* Since `rlang::lang()` is soft-deprecated and gives warning instructing to switch to `call2()`
> Replace `lang()` with `call2()`

- FP.Rmd
- Function-factories.Rmd
- Meta.Rmd
- Translation.Rmd
I left `first class function(s)`, but modified to compound modifier for env't(s). (IMHO, first-class functions should get a hyphen, too. Just LMK). 😳
> Hyphenate first-class environments

- Vectors.Rmd
indistinguisable -> indistinguishable
suprisingly -> surprisingly
> Fixes two typos

- R6.Rmd
This was a _lot_ easier to follow than the S4 chapter, and I don't think that's just because R6/RC is class-based rather than generic-based - I think it's because single inheritance allows you to avoid a boatload of emoji diagrams. As I mention twice in the chapter, I think S3 -> R6 -> S4 will be a much gentler reading order than historical order.
> Comments on R6 chapter

- S3.Rmd
This PR corrects a trivial typo: `allows` -> `always` as the intention of the sentence seems to be:
> If you do, the method will always return the same class, regardless of the input.
> Typo: allows -> always

- S3.Rmd
Minor changes listed below in order of appearance (in case they're ambiguous):
* Missing comma
* Use "a generic" as you do elsewhere
* Missing word
* Subject agreement between two sentences
* Reiterating that it's about validators
* Errant line break
* Conditional comma
* Compound modifier  
* Added comma  
* Missing word  
* Stay in tense
> Copy edit S3 chapter

- Functionals.Rmd
Since `x` has not be defined, `list(f(1), f(2), f(3))` is clearer
If keeping `list(f(x[[1]]), f(x[[2]]), f(x[[3]]))` is important, then it might be
good to define `x <- 1:3` just before
> Suggest expression change

- Function-factories.Rmd
I spotted a duplicate of word 'example' in the paragraph when reading the book online. I believe it is an typo and hopefully the proposal could help a little. I assign the copyright of this contribution to Hadley Wickham
> Update Function-factories.Rmd to remove duplicate of word

- Rcpp.Rmd
The C++ community seems to have converged to using cppreference as the "go to" place for online documentation and reference of the standard.  A key advantage is that cppreference is a community wiki -- an open platform as opposed to a closed one -- and generally have higher quality content. Another is that it doesn't have advertisements.
See the discussions here:
- https://stackoverflow.com/questions/6520052/whats-wrong-with-cplusplus-com
- https://meta.stackexchange.com/questions/194788/links-being-changed-to-cppreference-com
While the answers do not completely settle the issue, I find the arguments for preferring cppreference over cplusplus convincing.
> Change reference link to cppreference

- Rcpp.Rmd
This is a continuation of #1347 (replacing cplusplus.com with cppreference). Somehow, I missed these other links the first time around - sorry about that!
> More cppreference links - continuation of #1347

- Environments.Rmd
```
Warning: `env_bind_exprs()` is soft-deprecated as of rlang 0.3.0.
Please use `env_bind_lazy()` instead.
This warning is displayed once per session.
```
```
Warning: `env_bind_fns()` is soft-deprecated as of rlang 0.3.0.
Please use `env_bind_active()` instead.
This warning is displayed once per session.
```
> update deprecated rlang functions for enviroment

- Functions.Rmd
... otherwise `.rowNamesDF<-` is missing in the list.
> Small correction in Functions exercise

- R6.Rmd
In https://adv-r.hadley.nz/r6.html#adding-methods-after-creation
```r
Accumulator <- R6Class("Accumulator")
Accumulator$set("public", "sum", 0)
Accumulator$set("public", "add", function(x = 1) {
self$sum <- self$sum + x 
})
```
`$set` does not return `self`
So sub class can't chain methods
```r
AccumulatorChatty <- R6Class("AccumulatorChatty", 
inherit = Accumulator,
public = list(
add = function(x = 1) {
cat("Adding ", x, "\n", sep = "")
super$add(x = x)
}
)
)
x2 <- AccumulatorChatty$new()
x2$add(10)$add(1)$sum
```
```
Adding 10
Error in x2$add(10)$add : $ operator is invalid for atomic vectors
```
> not modify Accumulator class in "14.2 Classes and methods"

- Subsetting.Rmd
recycling: "This is convenient and easy to  understand when one of `x` and `y` is length one, but I recommend avoiding recycling for other lengths because the rules are consistently applied throughout base R."
"inconsistently applied" or "too consistently" (recycling based on multiples of length might not be what you want)
> Subsetting: Selecting multiple elements

- Meta.Rmd
- Techniques.Rmd
Makes the URL look like
GOOD, unnumbered:
https://adv-r.hadley.nz/techniques.html
instead of
YUCK:
https://adv-r.hadley.nz/introduction-22.html
> Explicit anchors for part introductions

- Subsetting.Rmd
I used \mbox{} to avoid hyphenated words in titles.
> subsetting edited

- Environments.Rmd
* p. 158 "their environments are called closures, which is why this term is often used interchangeably with function in R’s documentation."    
Asks for "function" to use monospace. Since is not code, I left it as is. 
* p. 168 "which context to return() to when a function completes"    
Asks for "to" to be in monospace. Is not code so I left it as is.
> Environments

- Names-values.Rmd
Unimportant comment: At the beginning of section **2.3.3 List** the editor suggests "Names (i.e. variables) point to values;...". I made the change but I think that the original version sounds better.
> Names and values edited

- base-types.Rmd
* p.291 Editor asks to remove hyphen in "object-oriented". The words appear throughout the book with and without hyphens. I don't know if there's a meaningful disctinction between the two. Should we choose a nomenclature and change it throughout?
> Base Types

- Meta.Rmd
I found that chapter overviews in each introductory part do not share the same style. 
* In introduction to Foundations, is "You use vectors every day in R, so Chapter 3 will dive..."
* In Functional programming is "Chapter 9 shows you how to... "
* In Metaprogramming is "In Big picture, Chapter 17, you’ll get..."
* In Techniques is in paragraphs instead of bullet points.
I don't know if this is intentional but it may be worth revising.
> Metaprogramming introduction

- Translation.Rmd
p. 487 The bold italic text is not showing. The tag functions created by the example fail if they don't have any named arguments because `dots_partition` fails when no argument is named. I added a check in `dots_partition` that fixes the bug.
> Translation

- Control-flow.Rmd
* p.97 Asks for "for loop" to be in monospace. I left it as is in light of the previous correction (https://github.com/hadley/adv-r/pull/1482/files/c02c21c9a27734e3f2a760a294ac30ebd70645b0#diff-8e73443dc8245dbb3244c3b6fa3b8113)
> Control Flow

- Evaluation.Rmd
I think that this sidenote is not in the right place. It refers to source2() so I moved it to where I suppose it belongs and makes sense to me, in section 20.2.2 . I appended it to the end of the section, but it could go before the last paragraph as well.
> Move a sidenote to another section in Evaluation.Rmd

- C-interface.Rmd
- Control-flow.Rmd
- Expressions.Rmd
- Foundations.Rmd
- Functionals.Rmd
- Introduction.Rmd
- Meta.Rmd
- Names-values.Rmd
- OO.Rmd
- Perf-improve.Rmd
- Quotation.Rmd
- Rcpp.Rmd
- S4.Rmd
- Subsetting.Rmd
- Techniques.Rmd
- Vectors.Rmd
This fixes some global problems. 
* It removes all quotemarks around blockquotes.
* Makes sure there are no "he or she" or "him or her".
* Removes capitalization in "Quiz **A**nswers".
* Rewrites chapter overviews so that they match in style. The OO part didn't have a chapter overview so I wrote one. I don't know exactly *where* it would go, though. 
I need to solve some issues but I need your input:
* Some tables have captions (Tables 19.1 and 19.2) but the rest don't. Should every table (and figure?) have a caption?
* When citing books and other resources sometimes they are around quotes (`...I found "Concepts, Techniques and Models of Computer Programming" [@ctmcp] extremely helpful.`) while others are italicised (`...the terminology of _Extending R_ [@extending-R] and call...`). …
> Global changes

- Vectors.Rmd
The sentence previously read as if 'never coerces strings to factors' related to the print method for tibbles, whereas it should relate to tibbles more generally.
> Possible typo in Quiz answers

- C-interface.Rmd
A cursory read of the text as is had me scratching my head about where `cfunction` is coming from if not `pryr`.
Closer read found the Prerequisites section, which mentions both `pryr` and `inline`. So it's a bit odd that `library(pryr)` is surfaced but `library(inline)` is not.
So, surfacing it here for future readers like me :)
> Move inline more prominently into code

- Functions.Rmd
Should this be `with_dir()`, to refer to the function defined around line 995 of the chapter? (Or, if it's `in_dir()` in a CRAN package then specify which package?)
> Possible typo

- Big-picture.Rmd
"I assign the copyright of this contribution to Hadley Wickham".
> Typo, deleting unnecessary "to"

- Evaluation.Rmd
`df` was not defined in the select2 function. I suppose `data` was meant instead. The function does not work when df is not defined in the global env otherwise.
> wrong variable name

- Functions.Rmd
This works because you defined `x <- 20` on line 473, but it doesn't make any sense in the context of the discussion of promises.
> Fix typo in Promises

- Evaluation.Rmd
Based on the code in this section, doesn't it make sense to write `eval(get_expr(q1), get_env(q1))` rather than `eval(get_expr(q1), get_env(q2))`? Also corrected a little typo in the same section.
> Small error in example, Section 20.3.2

- Quotation.Rmd
Line 912 - "homonoyms" to "homonyms". Thanks.
> Typo in quasiquotation

- Perf-improve.Rmd
`selectMethod` should be recommended since `getMethod` does not handle inheritance.
> Use `selectMethod` instead of `getMethod`

- Rcpp.Rmd
Apologies for the URL change -- updated static github site to blogdown, will now be stable for the forseeable future. Thanks for the link.
> Update URL for Rcpp example

- Functions.Rmd
The example above defines `with_dir()`. Looks like the example used to define `in_dir()` and this question needs to be updated.
> Fix typo: in_dir() -> with_dir()

- S4.Rmd
I think this is a typo, the `is` example returns FALSE because the capitalization of the class name is wrong.
``` r
library(methods)
setClass("Person", 
slots = c(
name = "character", 
age = "numeric"
), 
prototype = list(
name = NA_character_,
age = NA_real_
)
)
john <- new("Person", name = "John Smith", age = NA_real_)
is(john, "person")
#> [1] FALSE
is(john, "Person")
#> [1] TRUE
```
<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> make `is` example clearer

- Functionals.Rmd
`simple_map2` works for the xs and ws provided, but using `xs` to set the length of the output vector could cause some unexpected behavior (e.g., 5 `NULL`s in the output vector if making `xs` and `ws` length-3 vectors).
> Change output vector initialization

- Vectors.Rmd
Changed the example object names in the first chunk in https://adv-r.hadley.nz/vectors-chap.html#attr-dims, in order to avoid giving a function name to an object `c <- ...` I renamed all the examples in the chunk from a, b, c to x, y, z.
> Update Vectors.Rmd to avoid object names overwriting base functions

- OO.Rmd
There was a tiny typo in line 58 (`an encapsulated` was written `a encapsulated`).
> Minor typo (a vs. an) OO.Rmd

- R6.Rmd
In the paragraph prior to 14.3.2 Active fields, this edit would replace "[what] it's [ok]" with "[what] is [ok]" in the following sentence: "The distinction between public and private fields is important when you create complex networks of classes, and you want to make it as clear as possible what is ok for others to access."
> Typo fix in 14.3.1

- Conditions.Rmd
We are prone to hurriedly converting variables that "look like" numerical data into numeric, without thoroughly investigating to check whether there are some "illegal" characters that exist e.g. commas, "+", hyphens, etc. These leads to NAs which should have been avoided in the first place. We are often prone to ignoring warnings, but this is an "error" that should never be ignored.
> Added an example where a warning should definitely be an error

- R6.Rmd
Python naming convention for the reference to the object itself is `self`, not `this`.
> Python naming convention is `self`, not `this`

- Vectors.Rmd
Currently, the two ways described to remove names from a vector are different:
- `unname()` prints the result, but does not update `x`
- `names(x) <- NULL` updates `x`
A reader may interpret the preceding text "you can remove names from a vector" as `x` being updated. This proposal change explicitly updates `x`.
> consistent approaches to removing vector names

- index.rmd
The link on the first edition page was pointing back to the first edition. I updated the link to point to the second edition.
> Update redirect from 1st edition to 2nd edition

- S4.Rmd
The [contributors page](https://www.r-project.org/contributors.html) says explains that Martin is no longer an R core member:
>  Martin Morgan up to June 2021.
This PR is just to reflect that
> Update status of Martin Morgan

- Subsetting.Rmd
A small edit to note that `[[` can do partial matching too, but not by default.
> Edit in Subsetting chapter

- Introduction.Rmd
I am currently getting a 404, page does not exist, message at http://klutometis.github.io/roxygen/. Correcting to https://roxygen2.r-lib.org/.
> Fix roxygen2 link

- Quotation.Rmd
Minor spelling / terminology correction - spatting => splatting.
Per contribution guidelines: I assign the copyright of this contribution to Hadley Wickham.
> Correct spelling error in Quotation.Rmd: spatting => splatting

- Function-operators.Rmd
> Correct purrr function name

- Perf-measure.Rmd
For me the exercise was not working as the GC was called too often? It is maybe only because my computer is too slow? Therefore I changed the torture to a higher integer than TRUE (1).
The torture flag takes an integer `profvis::profvis(torture = step)`  as in the background it uses `base::gctorture2` 
https://github.com/rstudio/profvis/blob/master/R/profvis.R
https://stat.ethz.ch/R-manual/R-devel/library/base/html/gctorture.html
Result from the exercise, with `torture=10`.
> Update Perf-measure.Rmd - profvis torture flag

- Functionals.Rmd
Fixed typo in function name of one example
> boostrap_summary() -> bootstrap_summary()

- Functions.rmd
This was by mistake pointing to the style guide.
> Fix link to functions chapter in second edition

- Vectors.Rmd
Under #df-create, the first example doesn't show the character column as a factor, presumably because this was written under R < 4.0.0 but now run under R >= 4.0.0.
> stringsAsFactors defaults to FALSE as of R 4.0.0

- Rcpp.Rmd
The `find()` and `count()` function was linking to the R function definition, it should in this case link to the corresponding C++ unordered set methods.
> Update Rcpp.Rmd - Overwrite wrong auto-links to R Functions

- Function-operators.Rmd
Same typo as in https://github.com/hadley/adv-r/pull/1688
`file.download()` should be corrected to `download.file()`
Cheers
Hannes
> Update Function-operators.Rmd - Typo

- Translation.Rmd
Slight change of language to say that functions generated by `void_tag()` error when given "child tags", rather than "unnamed tags" and that those child tags are captured by "unnamed dots".
> Refine void_tag() description

- Function-factories.Rmd
The `boot_model()` function does not have a `model` argument. It does have `formula`.
https://github.com/hadley/adv-r/blob/1ab83672ad077400b842938804a3773f4279115c/Function-factories.Rmd#L554-L563
> Fix typo in Factories exercise: model --> formula

- Quotation.Rmd
Typo: `purr::reduce()` is missing an "r".
> Update Quotation.Rmd -- typo in `purr::reduce()`

- Function-operators.Rmd
I may be missing a deeper point here, but it seems simpler for `chatty()` to use `message()` instead of `cat()` and call it before the processing begins?
> Tighten `chatty()` example
